function str = postprocessing_paraview(str,filename)

%--------------------------------------------------------------------------
% Shape functions and mesh re-arrangement    
%--------------------------------------------------------------------------
str              =  shape_functions_mesh_postprocessing_paraview(str);
%--------------------------------------------------------------------------
% Initialisation of variables to obtain in the postprocessing.
%--------------------------------------------------------------------------
str              =  postpocessing_initialisation_paraview(str);
%--------------------------------------------------------------------------
% Postprocessing per element of all the postprocessing variables in the 
% postprocessing mesh.
%--------------------------------------------------------------------------
str              =  postpocessing_computing_paraview(str);
%--------------------------------------------------------------------------
% Method to compute the variables in the vertices(output type): averaging...
%--------------------------------------------------------------------------
str              =  nodal_average_paraview(str);
   
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
% Variables to plot in Paraview 
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
% displacements and phi
%--------------------------------------------------------------------------
ux               =  (str.postproc.displacement(1,:))';
uy               =  (str.postproc.displacement(2,:))';
uz               =  (str.postproc.displacement(3,:))';
phi              =  str.postproc.phi;
%--------------------------------------------------------------------------
% Cauchy stress and different contributions.
%--------------------------------------------------------------------------
SigmaF11         =  reshape(str.postproc.SigmaF(1,1,:),[],1,1);
SigmaF12         =  reshape(str.postproc.SigmaF(1,2,:),[],1,1);
SigmaF13         =  reshape(str.postproc.SigmaF(1,3,:),[],1,1);
SigmaF21         =  reshape(str.postproc.SigmaF(2,1,:),[],1,1);
SigmaF22         =  reshape(str.postproc.SigmaF(2,2,:),[],1,1);
SigmaF23         =  reshape(str.postproc.SigmaF(2,3,:),[],1,1);
SigmaF31         =  reshape(str.postproc.SigmaF(3,1,:),[],1,1);
SigmaF32         =  reshape(str.postproc.SigmaF(3,2,:),[],1,1);
SigmaF33         =  reshape(str.postproc.SigmaF(3,3,:),[],1,1);
 
SigmaH11         =  reshape(str.postproc.SigmaH(1,1,:),[],1,1);
SigmaH12         =  reshape(str.postproc.SigmaH(1,2,:),[],1,1);
SigmaH13         =  reshape(str.postproc.SigmaH(1,3,:),[],1,1);
SigmaH21         =  reshape(str.postproc.SigmaH(2,1,:),[],1,1);
SigmaH22         =  reshape(str.postproc.SigmaH(2,2,:),[],1,1);
SigmaH23         =  reshape(str.postproc.SigmaH(2,3,:),[],1,1);
SigmaH31         =  reshape(str.postproc.SigmaH(3,1,:),[],1,1);
SigmaH32         =  reshape(str.postproc.SigmaH(3,2,:),[],1,1);
SigmaH33         =  reshape(str.postproc.SigmaH(3,3,:),[],1,1);

SigmaJ           =  str.postproc.SigmaJ;
%--------------------------------------------------------------------------
% Cauchy stress and different contributions.
%-------------------------------------------------*------------------------
sigma11          =  reshape(str.postproc.sigma(1,:),[],1);
sigma22          =  reshape(str.postproc.sigma(2,:),[],1);
sigma33          =  reshape(str.postproc.sigma(3,:),[],1);
sigma12          =  reshape(str.postproc.sigma(4,:),[],1);
sigma13          =  reshape(str.postproc.sigma(5,:),[],1);
sigma23          =  reshape(str.postproc.sigma(6,:),[],1);

pressure         =  reshape(str.postproc.sigma_pressure,[],1);
%--------------------------------------------------------------------------
% Electric displacement. Eulerian part.
%--------------------------------------------------------------------------
Dx               =  reshape(str.postproc.D(1,:),[],1);
Dy               =  reshape(str.postproc.D(2,:),[],1);
Dz               =  reshape(str.postproc.D(3,:),[],1);
%--------------------------------------------------------------------------
% Electric displacement. Lagrangian part.
%--------------------------------------------------------------------------
D0x              =  reshape(str.postproc.D0(1,:),[],1);
D0y              =  reshape(str.postproc.D0(2,:),[],1);
D0z              =  reshape(str.postproc.D0(3,:),[],1);
%--------------------------------------------------------------------------
% Electric field.
%--------------------------------------------------------------------------
Ex               =  reshape(str.postproc.E(1,:),[],1);
Ey               =  reshape(str.postproc.E(2,:),[],1);
Ez               =  reshape(str.postproc.E(3,:),[],1);
E0x              =  reshape(str.postproc.E0(1,:),[],1);
E0y              =  reshape(str.postproc.E0(2,:),[],1);
E0z              =  reshape(str.postproc.E0(3,:),[],1);
%--------------------------------------------------------------------------
% Deformation.
%--------------------------------------------------------------------------
F11              =  reshape(str.postproc.F(1,1,:),[],1,1);
F12              =  reshape(str.postproc.F(1,2,:),[],1,1);
F13              =  reshape(str.postproc.F(1,3,:),[],1,1);
F21              =  reshape(str.postproc.F(2,1,:),[],1,1);
F22              =  reshape(str.postproc.F(2,2,:),[],1,1);
F23              =  reshape(str.postproc.F(2,3,:),[],1,1);
F31              =  reshape(str.postproc.F(3,1,:),[],1,1);
F32              =  reshape(str.postproc.F(3,2,:),[],1,1);
F33              =  reshape(str.postproc.F(3,3,:),[],1,1);

H11              =  reshape(str.postproc.H(1,1,:),[],1,1);
H12              =  reshape(str.postproc.H(1,2,:),[],1,1);
H13              =  reshape(str.postproc.H(1,3,:),[],1,1);
H21              =  reshape(str.postproc.H(2,1,:),[],1,1);
H22              =  reshape(str.postproc.H(2,2,:),[],1,1);
H23              =  reshape(str.postproc.H(2,3,:),[],1,1);
H31              =  reshape(str.postproc.H(3,1,:),[],1,1);
H32              =  reshape(str.postproc.H(3,2,:),[],1,1);
H33              =  reshape(str.postproc.H(3,3,:),[],1,1);

J                =  str.postproc.J;

%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
% Create Paraview file. 
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
VTK_plotting(filename,'unstructured_grid',str.postproc.Eulerian_x',str.postproc.connectivity,'scalars','ux',ux,...
                                                                            'scalars','uy',uy,...
                                                                            'scalars','uz',uz,...
                                                                            'scalars','phi',phi,...
                                                                            'scalars','SigmaF11',SigmaF11,...
                                                                            'scalars','SigmaF12',SigmaF12,...
                                                                            'scalars','SigmaF13',SigmaF13,...
                                                                            'scalars','SigmaF21',SigmaF21,...
                                                                            'scalars','SigmaF22',SigmaF22,...
                                                                            'scalars','SigmaF23',SigmaF23,...
                                                                            'scalars','SigmaF31',SigmaF31,...
                                                                            'scalars','SigmaF32',SigmaF32,...
                                                                            'scalars','SigmaF33',SigmaF33,...
                                                                            'scalars','SigmaH11',SigmaH11,...
                                                                            'scalars','SigmaH12',SigmaH12,...
                                                                            'scalars','SigmaH13',SigmaH13,...
                                                                            'scalars','SigmaH21',SigmaH21,...
                                                                            'scalars','SigmaH22',SigmaH22,...
                                                                            'scalars','SigmaH23',SigmaH23,...
                                                                            'scalars','SigmaH31',SigmaH31,...
                                                                            'scalars','SigmaH32',SigmaH32,...
                                                                            'scalars','SigmaH33',SigmaH33,...
                                                                            'scalars','SigmaJ',SigmaJ,...
                                                                            'scalars','sigma11',sigma11,...
                                                                            'scalars','sigma22',sigma22,...
                                                                            'scalars','sigma33',sigma33,...
                                                                            'scalars','sigma12',sigma12,...
                                                                            'scalars','sigma13',sigma13,...
                                                                            'scalars','sigma23',sigma23,...
                                                                            'scalars','pressure',pressure,...
                                                                            'scalars','Dx',Dx,...
                                                                            'scalars','Dy',Dy,...
                                                                            'scalars','Dz',Dz,...
                                                                            'scalars','D0x',D0x,...
                                                                            'scalars','D0y',D0y,...
                                                                            'scalars','D0z',D0z,...                                                                            
                                                                            'scalars','Ex',Ex,...
                                                                            'scalars','Ey',Ey,...
                                                                            'scalars','Ez',Ez,...
                                                                            'scalars','E0x',E0x,...
                                                                            'scalars','E0y',E0y,...
                                                                            'scalars','E0z',E0z,...
                                                                            'scalars','F11',F11,...
                                                                            'scalars','F12',F12,...
                                                                            'scalars','F13',F13,...
                                                                            'scalars','F21',F21,...
                                                                            'scalars','F22',F22,...
                                                                            'scalars','F23',F23,...
                                                                            'scalars','F31',F31,...
                                                                            'scalars','F32',F32,...
                                                                            'scalars','F33',F33,...
                                                                            'scalars','H11',H11,...
                                                                            'scalars','H12',H12,...
                                                                            'scalars','H13',H13,...
                                                                            'scalars','H21',H21,...
                                                                            'scalars','H22',H22,...
                                                                            'scalars','H23',H23,...
                                                                            'scalars','H31',H31,...
                                                                            'scalars','H32',H32,...
                                                                            'scalars','H33',H33,...
                                                                            'scalars','J',J)
                                                                            
                                                                        
                                                                        
                                                                        
                                                                        
                                                                        
                                                                        